[model_providers.lms]
name = "LM Studio"
base_url = "http://localhost:1234/v1"

[profiles.local-model]
model_provider = "lms"
# model = "qwen3-coder-next-mlx@4bit"
# model = "qwen3.5-122b-a10b-ram-60gb-mlx"
model = "huihui-qwen3.6-35b-a3b-claude-4.7-opus-abliterated-mlx"

